language: java
sudo: false
script: mvn install
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "TheNiggo"
  - git config --local user.email "nick200108@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: mV3N0uNMTYTC2k5oNp8DVuKeFMPfJK2JRs/cGc0GQdmKfZmX5+IKyXO0d253CW5RxHR/wJIJzLoTG5/vX3wjzaZbk0w8duPO7vfDu1oDOsYAquL/KdjvmRiK0ajpy4RV5D7odcNxCkZuSmLIrEjQk+dkp7nyzFfN498p83Pp/uFbSAuAqwRYjC1DkUT/WXYZxGaXcGfQ/B+37DaCPmGR5FCAgc8XxzCloZCMVR8VhnXqS7+6Bn94azRYJU2FOjqc1rTuuRp5juXm+WZCvh9nZZNK2QpJd+rpzMqqvL34bA4lrMSXl9By3j8jP2U1FycJaxl8Jy17N52awTcZGV4Tu6V4EXE4ni9nng2q73ikbdujn4MQZ/2PqZNZ4+ZQj0c6FKYN9GjZ6SASIBYwucEQVcIssMSNAL9biuKe1zSwO4mwHTptQW6iyvwBvdYraeXnFTcQMGComDEXu4ufEbWPz5rxoGHauNCpq0RR0vqjsxu7y8aCcaHmbo0tkKgjLazVogCW6eXbVu/pm7yN0OkpFjDsOyslpLCjGrWjbaiGmH75i4/AxR/hQCvp22tik5WiQU3Cy09/twFm1nKaZGVybENzD2KZLATimQ/wbW+o2H46Nq+VT0Ue8kutX8LSEsH/tpEkjv4KCNdaQZh2EnulARKHiCbLb+jEcLOlZlpEqaE=
  file: "/home/travis/build/TheNiggo/CalculatorMaven/target/CalculatorMaven-1.0-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    repo: TheNiggo/CalculatorMaven

